name: auto_recorder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'
dependencies: 
  app_settings: ^5.1.1
  async: ^2.11.0
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.6
  flutter: 
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  just_audio: ^0.9.37
  mic_stream: ^0.7.1
  path: ^1.8.3
  path_provider: ^2.1.3
  permission_handler: ^11.0.1
  record: ^5.0.5
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.3
dev_dependencies: 
  build_runner: ^2.4.9
  custom_lint: any
  file: ^7.0.0
  flutter_test: 
    sdk: flutter
  freezed: any
  isar_generator: any
  mockito: ^5.4.4
  pedantic_mono: any
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^2.4.0
  yumemi_lints: ^1.7.0
flutter: 
  assets: 
    - assets/pcm_16bit_mono.raw
  uses-material-design: true
